export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_ATTENDANCE_RECORDS_SUCCESS = 'FETCH_ATTENDANCE_RECORDS_SUCCESS';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';